apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-server
  labels:
    app: was
spec:
  selector:
    matchLabels:
      app: was
  template:
    metadata:
      name: backend-server
      labels:
        app: was
    spec:
      containers:
        - name: was
          image: jjj920217/backend:2404230621_2
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 150m
            limits:
              cpu: 180m
