apiVersion: apps/v1
kind: Pod
metadata:
  name: backend-server
  labels:
    app: was
spec:
  containers:
    - name: was
      image: jjj920217/backend:2404230621_2
      ports:
        - containerPort: 8080
      resources:
        requests:
          cpu: 250m
        limits:
          cpu: 300m
