apiVersion: v1
kind: Pod
metadata:
  name: frontend-server
  labels:
    app: web
spec:
  containers:
    - name: web
      image: jjj920217/frontend:2404230620_10
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: 100m
        limits:
          cpu: 150m
