apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: web
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30082
